### ISSUE TITLE
Bootstrap class autocomplete suggestion doesn't popup automatically

### ISSUE THREAD

**Issue by FaridLU** [Eventyret/vscode-bcdn#12]
Whenever I write bootstrap class name outside of the class section it shows suggestions automatically, like this:
![1](https://user-images.githubusercontent.com/37978468/54083883-b6384b80-4353-11e9-94c9-7a8bf1b8ec2f.png)

but when I try to write bootstrap class name inside the class section, the autocomplete suggestions doesn't popup automatically, but when I press ctrl+space the suggestion popup succesfully. I think this should be fixed. 

![2](https://user-images.githubusercontent.com/37978468/54083920-48405400-4354-11e9-8608-5ecf3f6f337f.png)

Thank you.

**Comment by Eventyret** [comment]
So this would not be the case for it it's ment to use outside of it. I think it should have been removed as well.
Justify Content center should just be a class so when your adding it, auto complete i think you need a language service or something.
