### ISSUE TITLE
!bcdn not work

### ISSUE THREAD

**Issue by SRsieam** [Eventyret/vscode-bcdn#24]
Issue Type: <b>Bug</b>

PLz help

Extension version: 1.8.0
VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (2.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Eventyret** [comment]
did you execute this on an HTML page without an HTML page it will not work @SRsieam

**Comment by Eventyret** [comment]
Any news on this @SRsieam  :)

**Comment by Eventyret** [comment]
Closing this as its 29 days old with no reply. Please make a new comment if you have further problems.
